# Generated by Django 5.2.4 on 2025-07-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avaible',
            new_name='available',
        ),
    ]
